(rule
 (alias runtest)
 (deps (source_tree regressions))
 (action (run ./regressions/run.sh)))

(rule
 (alias runtest)
 (deps (source_tree regressions))
 (action (run ./regressions/run_exec_add_funspec.sh)))

(rule
 (alias runtest)
 (deps (source_tree regressions))
 (action (run ./regressions/run_funspec_scope.sh)))

(rule
 (alias runtest)
 (deps (source_tree regressions))
 (action (run ./regressions/run-payload-shapes.sh)))

(rule
 (alias runtest)
 (deps (source_tree regressions))
 (action (run ./regressions/run-contract-frontier.sh)))
